### ISSUE TITLE
Rounded Corners Pull Request

### ISSUE THREAD

**Issue by abhibeckert** [chillerlan/php-qrcode#127]
I've written a custom output class to generate rounded corners, like this:

<img width="354" alt="Screen Shot 2022-05-25 at 14 00 15" src="https://user-images.githubusercontent.com/266088/170177149-cdfda0ac-8e07-4b2f-b63c-7c6899203354.png">

It works fine for my use case, but would you be interested in a pull request? If you are then I'll clean it up, write some tests, etc.

Also it currently only outputs to SVG. Which is all I need myself, I wouldn't want to write the code to do rounded corners as a bitmap...

**Comment by codemasher** [comment]
Wow! That looks great! A PR would be much appreciated! I'll see if it can be at least implemented in the ImageMagick output, GD seems [too clunky to draw round corners anyway](https://github.com/chillerlan/php-qrcode/blob/3d99ee99dcd716d6daab064102dfef490772c6be/src/Output/QRGdImage.php#L91)...

**Comment by walidaalhomsi** [comment]
@abhibeckert thanks for sharing your experience, if PR needs a lot of cleaning and tests ...  can you share the snippet which creates the rounded corners here?

**Comment by abhibeckert** [comment]
So the main challenge I had is SVG doesn't seem to handle shapes that touch each other - it tends to draw hairline cracks in between. I wasn't able to completely eliminate the issue but I was able to get pretty close by overlapping shapes... which is mostly where the code became messy as I was it was largely trial end error with minimal planning.

Here's my test code: https://gist.github.com/abhibeckert/2bfb6a884c7fdd3194af86bd28ef9c10

I will clean it up some time soon as I plan to use it in production.

**Comment by codemasher** [comment]
The hairlines happen when the modules are not in the same `<path d>` element - see #57 - or in your case it's probably the individual `<use>` elements.

**Comment by walidaalhomsi** [comment]
Thanks for sharing your code, it is really helpful.

**Comment by codemasher** [comment]
Oh, i forgot to mention that [I've added some `isset()` in `QRMatrix`](https://github.com/chillerlan/php-qrcode/commit/964f37ba9601030aae8c3bcb331cee908be9b0eb) to make several sanitiy checks obsolete, among other things.
Check out the latest version:
`composer require chillerlan/php-qrcode:dev-main#cde2af576b6b829b1a30e3042eba488c90d94478`

**Comment by codemasher** [comment]
This is it:
```php
$bits  = $this->checkNeighbours($x, $y, $M_TYPE);
$check = fn(int $all, int $any):bool => ($bits & ($all | (~$any & 0xff))) === $all;

// 1 2 3
// 8 # 4
// 7 6 5

// checking if a rounded corner on 1 (top left) only is valid
// for this, the right (4) and bottom edge (6) must have neighbours, top (2) and left (8) must not
// neighbours on the corners (1,3,5,7) are optional
// $bits = 0b00101101
$check(0b00101000, 0b01010101); // -> true
```

**Comment by codemasher** [comment]
Ok, so i have implemented the thing, [code over here](https://github.com/chillerlan/php-qrcode/blob/62c0a94e3ac7ede384a6c729e0726d8c77115488/examples/svgMeltedModules.php). Turns out it is surprisingly tricky to recreate the effect in an ImageMagick raster image as there seems no easy way to just draw a path and fill it with a color. However, it always possible to convert the SVG to a raster image [via the Inkscape command line interface](https://superuser.com/questions/381125).

The result looks something like this: 
![svgMeltedModules](https://user-images.githubusercontent.com/592497/178153699-824df04c-b7e4-4070-b054-1eb39499d6b6.svg)

I have also added an option to inverse the effect, so that it "flows" along the dark modules:
![svgMeltedModules-inverse](https://user-images.githubusercontent.com/592497/178153733-2baa9b0d-1c0a-4ed2-a7cd-3b172cc83b46.svg)

**Comment by abhibeckert** [comment]
@codemasher there's a bug in your example code.

Specifically this line:

    if($this->options->connectPaths && $this->matrix->checkTypeNotIn($x, $y, $this->options->excludeFromConnect)){

Fails because `checkTypeNotIn` doesn't exist. It needs to be `checkTypeIn` (and obviously add a `!` operator).

**Comment by kusiu** [comment]
@codemasher the example doesnt seem to be working with latest version.

**Comment by codemasher** [comment]
@kusiu it works fine with `5.0-beta` or the `dev-main` branch, it won't work with v4.3.x.

**Comment by abhibeckert** [comment]
@codemasher I've added one more tweak:

    .dark {stroke: url(#grad); stroke-width: 0.01;}

(replace the gradient with a solid color, if that's what you're using... I normally use a subtle gradient)

The extra stroke fixes the edge issues in this example (note this issue only occurs with some SVG renderers):

<img width="260" alt="image" src="https://github.com/chillerlan/php-qrcode/assets/266088/204b3d08-1999-47cb-b874-497237eec85e">

The slightly fatter dark blocks result in this:

<img width="261" alt="image" src="https://github.com/chillerlan/php-qrcode/assets/266088/a446718b-bd70-4da1-b2d9-bbc10381c5d3">

**Comment by codemasher** [comment]
Hey, thank you for the feedback! I'll check out adding a stroke, but so far i haven't run into the render issue again. 
Could you please post the raw SVG of both examples - I'm curious what causes the hairlines in the first one.

**Comment by YeftaAW** [comment]
Tried the example (examples/svgMeltedModules.php) but it doesn't seem working well. I tried with version 5.0-beta, 5.0.0, and above. Anyways I just copy paste the code. And here is the result
![svg](https://github.com/chillerlan/php-qrcode/assets/71545409/8712c485-c75c-43a6-ba2c-85338b1d19a8)

**Comment by YeftaAW** [comment]
I think this is only working with dev-main currently.

**Comment by codemasher** [comment]
@YeftaAW how so? Please open [a new discussion](https://github.com/chillerlan/php-qrcode/discussions) for your issue.
