### ISSUE TITLE
Get version of generated qr-code

### ISSUE THREAD

**Issue by maisen20** [chillerlan/php-qrcode#17]
first: thank you for this excellent script!

is there a function to get the qr-version of the generated qr-code when in options "version" is set to QRCode::VERSION_AUTO ?

**Comment by codemasher** [comment]
Hey, you're welcome! Did you try `QRMatrix::version()`? The matrix object holds the version number of the generated qr code and you can get hold of it if you render the code manually like so:

```php
// get the matrix object
$matrix = $qrcode->getMatrix($data);
// fetch the version number
$version = $matrix->version();
// continue render
$matrix->dump();
```
Hope that helps!

**Comment by maisen20** [comment]
okay thank you very much :)!

**Comment by codemasher** [comment]
i just realized that the `dump()` method is on the `QRDataInterface` but i think you'll get that managed :D

**Comment by codemasher** [comment]
fixed the above comments - today's not my day...
