### ISSUE TITLE
Suggest update chillerlan/php-settings-container >= 3.0

### ISSUE THREAD

**Issue by monta990** [chillerlan/php-qrcode#179]
https://github.com/chillerlan/php-qrcode/blob/fbb4811094940f125657297b74d34b541512c501/composer.json#L40

Its possible update to 3.0?

**Comment by codemasher** [comment]
I keep track of my own packages and i would have done so if it was possible. A [second of research](https://packagist.org/packages/chillerlan/php-settings-container) would have revealed the glaring issue with updating it.
