### ISSUE TITLE
Encoding binary QR codes is broken

### ISSUE THREAD

**Issue by 9072997** [chillerlan/php-qrcode#182]
**Describe the bug**
In commits before 4da90c5c3bc2b7aa1d28a31eba0c9681a892deeb it was possible to create QR codes containing binary data, such as those used by [Clever](https://support.clever.com/hc/s/articles/220213907?language=en_US). This is no longer possible.

**Steps to reproduce the behavior**
When I do
```php
$renderer = new chillerlan\QRCode\QRCode(
	new chillerlan\QRCode\QROptions([
		'outputType'   => chillerlan\QRCode\QRCode::OUTPUT_MARKUP_SVG,
		'eccLevel'     => chillerlan\QRCode\Common\EccLevel::M,
		'connectPaths' => true,
		'addQuietzone' => false,
		'imageBase64'  => false
	])
);
$svg = $renderer->render(hex2bin('01015989f47dff8e852122117e04c90b9f15defc1c36477b1fe1'));

header('Content-Type: image/svg+xml');
echo $svg;
```
I get the error message:
```txt
PHP Fatal error:  Uncaught chillerlan\QRCode\Data\QRCodeDataException: mb_detect_encoding error in C:\inetpub\wwwroot\photomgr\vendor\chillerlan\php-qrcode\src\Data\Kanji.php:62
Stack trace:
#0 C:\inetpub\wwwroot\photomgr\vendor\chillerlan\php-qrcode\src\Data\Kanji.php(82): chillerlan\QRCode\Data\Kanji::convertEncoding()
#1 C:\inetpub\wwwroot\photomgr\vendor\chillerlan\php-qrcode\src\QRCode.php(205): chillerlan\QRCode\Data\Kanji::validateString()
#2 C:\inetpub\wwwroot\photomgr\scratch.php(13): chillerlan\QRCode\QRCode->render()
#3 {main}
  thrown in C:\inetpub\wwwroot\photomgr\vendor\chillerlan\php-qrcode\src\Data\Kanji.php on line 62
```

**Expected behavior**
a QR-code like this one is generated (like it was in previous versions):
![image](https://user-images.githubusercontent.com/1310772/222226763-08985c79-76c1-4bde-b3e1-e1a9b418689a.png)

**Environment (please complete the following information):**
 - PHP version/OS: PHP 8.1.5 on IIS on Windows Server 2019
 - Library version: tested under d650fe73067c2559519f09949e9b71b466ab2bee

**Comment by codemasher** [comment]
Hmm, this is weird, i wonder how the auto detection passed as `Kanji`. I've made changes to the detection recently, so i guess i'll have to revisit this. However, you can circumvent the detection issue by forcing the renderer into a certain mode as demonstrated in [the multi mode example](https://github.com/chillerlan/php-qrcode/blob/main/examples/multimode.php).

**Comment by codemasher** [comment]
Wait no, the error is not because the binary string *passed* but because it produced an error during conversion to SJIS, which is technically the expected behaviour.

**Comment by codemasher** [comment]
Hey, i've pushed a little fix in https://github.com/chillerlan/php-qrcode/commit/cc58c403f8d24343276778713579e4798fa255fa - please let me know if it works for you or causes other issues! Thanks for helping to improve this library!

**Comment by 9072997** [comment]
cc58c403f8d24343276778713579e4798fa255fa resolves the issue. Thanks for the tip about forcing a mode and for this handy library :)
