### ISSUE TITLE
Composer require chillerlan/php-qrcode dont download last release even if is 4.3.4

### ISSUE THREAD

**Issue by InitialCrow** [chillerlan/php-qrcode#183]
Hi, ty for your job just litle thing

**Describe the bug**
When I try to get last release with composer its ^4.3 if I force to 4.3.4 nothing change so its missing many parts for exemple constant in /src/Output/OutputInterface.php

**Steps to reproduce the behavior**
Just do `composer require chillerlan/php-qrcode `

**Expected behavior**
Just download last release 4.3.4 like is on github main

**Screenshots**
Content of output folder

Without composer require just clone 

![Capture d’écran du 2023-03-07 15-55-54](https://user-images.githubusercontent.com/15141692/223459383-2e6fe7c3-751b-469c-94f9-d0ae012152f6.png)

And now with `composer require chillerlan/php-qrcode` or `composer require chillerlan/php-qrcode:4.3.4`

![Capture d’écran du 2023-03-07 15-56-04](https://user-images.githubusercontent.com/15141692/223459717-ddfcca59-d458-415d-8b41-1831878823c2.png)

**Environment (please complete the following information):**
 - PHP version/OS: [e.g. 7.4.12, Ubuntu 20.04]
 - Library version: [e.g. 4.3.1]

**Additional context**

**Comment by InitialCrow** [comment]
Whoopsi I suppose last commit not are release yet ohewer its on main

**Comment by codemasher** [comment]
Just fyi: [this is the 4.3.x branch](https://github.com/chillerlan/php-qrcode/tree/v4.3.x) where the release is tagged.

**Comment by InitialCrow** [comment]
Yep ty sorry for that
