### ISSUE TITLE
How to save the QR to the server?

### ISSUE THREAD

**Issue by nealoke** [chillerlan/php-qrcode#19]
Hi! This is probably a very noob question to ask but how do I save the QR code to my server folder? I've been using the QR library which this was based on but there you would call `QRcode::png($data, $filePath . $fileName, QR_ECLEVEL_H, 6, 1);` and it would be saved.

**Comment by nealoke** [comment]
Made it work with `file_put_contents()`, still think it would be nice if this was documented :)

**Comment by codemasher** [comment]
It's already built-in and documented: https://github.com/chillerlan/php-qrcode#qroptions-properties - see: `$cachefile`.
