### ISSUE TITLE
Render to variable

### ISSUE THREAD

**Issue by Criptos** [chillerlan/php-qrcode#21]
I haven't found a way  to store the image to a variable so I can base64encode it and store it at a database without writing it to filesystem...

**Comment by codemasher** [comment]
1. the image data is base64encoded by default, including the `data:image/<TYPE>;base64,` header
2. if you want to the image data explicitly, you can turn off base64 encoding by setting `QROptions::$imageBase64` to false.

The relevant code is here:
https://github.com/chillerlan/php-qrcode/blob/4241b55f3841872704fc31eecc49b18ab5751f59/src/Output/QRImage.php#L97-L101
