### ISSUE TITLE
[BUG]  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/chillerlan/php-qrcode/src/QRCode.php on line 218

### ISSUE THREAD

**Issue by GregJohnStewart** [chillerlan/php-qrcode#224]
**Describe the bug or unexpected behaviour**

As title discribes, getting the following error on my php 8.1 setup:

<b>Deprecated</b>:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in <b>vendor/chillerlan/php-qrcode/src/QRCode.php</b> on line <b>218</b><br />

**Steps to reproduce the behavior**

Run on php 8.1, render

Seems to only occur (breakingly) when have error reporting on:

```php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);
```

**Environment (please complete the following information):**

- PHP version/OS: 8.1, Linux
- Library version: 4.3.2

**Comment by codemasher** [comment]
this bug is fixed in v4.3.3 (#97, #110) - please update to the latest 4.x version.
