### ISSUE TITLE
rectangles to squares

### ISSUE THREAD

**Issue by muhamed-didovic** [chillerlan/php-qrcode#23]
Is there easy way to convert rectangles or squares to circles, or can you point me how can I do that?

**Comment by codemasher** [comment]
You mean the QR Code pixels? If that's what you're looking for, just create your own custom output class, extend `QRImage` andoverwrite the method `QRImage::setPixel()` like so (might need a bit adjustment):

```php
	protected function setPixel(int $x, int $y, int $color){
		imagefilledellipse(
			$this->image,
			($x * $this->scale) + ($this->scale / 2),
			($y * $this->scale) + ($this->scale / 2),
			$this->scale-1,
			$this->scale-1,
			$color
		);
	}
```
which then outputs something like this:

![image](https://user-images.githubusercontent.com/592497/42519690-e34d3148-8464-11e8-8331-159de6a4a779.png)

**Comment by antonioreyna** [comment]
how can i get those smooth circles? mine look sharp at the edges?

**Comment by codemasher** [comment]
I haven't looked into this further, but it appears that `imagefilledellipse()` makes the dots more square-y on smaller scale. You can see in the above screenshot that they're not perfectly round. I also haven't looked into `imagefilledarc()` yet, but it might be worth a try. I guess you won't get around writing a little custom function if you want (more or less) perfectly round dots.
