### ISSUE TITLE
Implement gitattributes

### ISSUE THREAD

**Issue by seebeen** [chillerlan/php-qrcode#234]
**Describe the feature**

Can a `.gitattributes` file be implemented? When downloading the package - entire project directory is downloaded to vendor dir - which (IMHO) is unneeded.

**Additional context**

Adding the .gitattributes will reduce the production package size.

**Are you (the requester) willing to submit a pull request for that feature?**

Yes, I'm willing to implement the pull request

**Comment by codemasher** [comment]
Hey, do you mean similar to this?
https://github.com/sebastianbergmann/phpunit/blob/63c8ce7363ad4c9f0ad2df314b4354058c88fcd4/.gitattributes

I could add that.

**Comment by codemasher** [comment]
Ok, I've added it - i went all the way and added `.gitattributes` files to the dependencies as well - you should get a nice clean vendor dir:
![image](https://github.com/chillerlan/php-qrcode/assets/592497/e41e59b2-599f-4b21-aea4-f84a5fd83d78)

**Comment by seebeen** [comment]
Awesome! Thanks for the quick response

**Comment by codemasher** [comment]
This is now available in v4.4.x and v5.0.x! 🚀
