### ISSUE TITLE
[BUG] php-qrcode does not apply Built-In Output Modules

### ISSUE THREAD

**Issue by cirolaferrara** [chillerlan/php-qrcode#249]
**php-qrcode does not apply Built-In Output Modules**

_outputInterface_ property was ignored

**Steps to reproduce the behavior**

```php
// Example 1
$options = new QROptions;
$options->outputInterface  = QRFpdf::class;

$fpdf = (new QRCode($options))->render($data);

var_dump($fpdf); // string(89214) "data:image/svg+xml;base64,...
```

```php
// Example 2
$options = new QROptions;
$options->outputInterface  = QRGdImageWEBP::class;

$fpdf = (new QRCode($options))->render($data);

var_dump($fpdf); // string(89214) "data:image/svg+xml;base64,...
```

**Expected behavior**

```php
// Example 1
var_dump($fpdf); // data:application/pdf;base64,...
```

```php
// Example 2
var_dump($fpdf); // data:image/webp;base64,...
```

**Environment (please complete the following information):**

- PHP version/OS: [PHP 8.2.9, Windows 11]
- Library version: 5.0, 5.0.1, 5.0.2

**Comment by codemasher** [comment]
Hi, this is not a bug. See https://github.com/chillerlan/php-qrcode/discussions/241#discussioncomment-8461662.

That being said, I think I need to point to the version branches in the Readme and or add a line to every single example doc block:

"Please use the examples from the branch that matches your installed php-qrcode version!"
