### ISSUE TITLE
PHP 7.1 

### ISSUE THREAD

**Issue by tessus** [chillerlan/php-qrcode#25]
I understand that you want to drop support for PHP 5.6 and even PHP7.

However, there's no technical reason for dropping 7.1 support. It should work perfectly fine on 7.1. There's a big difference between EOL and end of active support.

Otherwise this is a great library.

**Comment by codemasher** [comment]
The 2.0 branch will continue to support 7.0 and 7.1. The current master branch is supposed to be v3.0 to conform with some of the underlying dependencies.

**Comment by codemasher** [comment]
Yeah, you should be fine with something like `"chillerlan/php-qrcode": "^2.0"` - the `v2.0.x-php5` branch is an unsupported backport for the Drupal core.

**Comment by tessus** [comment]
Awesome, thanks again.

**Comment by codemasher** [comment]
You're welcome!
