### ISSUE TITLE
[BUG] Demo gives 500 Internal Server Error

### ISSUE THREAD

**Issue by timohausmann** [chillerlan/php-qrcode#253]
**Describe the bug or unexpected behaviour**

The demo at https://smiley.codes/qrcode/ does not work.

**Steps to reproduce the behavior**

- Go to https://smiley.codes/qrcode/ 
- use input "test" or any URL
- Press generate
- Watch impressive girl dance for an eternity
- After a while, open network dev tools and see this error:
- POST https://smiley.codes/qrcode/generator.php 500 (Internal Server Error)

**Expected behavior**

A QR Code instead of a dancing girl. Maybe add error handling to the frontend.

**Comment by codemasher** [comment]
Hi, thanks for the report, this is a known issue: https://github.com/codemasher/nova-qrcode/issues/2#issuecomment-2027807873

**Comment by codemasher** [comment]
This should be resolved with https://github.com/codemasher/nova-qrcode/commit/5c9e25573dc19686ceca27a0b9de21f11a50faf5

Please report back if you encounter any issues. Thank you!
