### ISSUE TITLE
[DOCS] PHP 8.1 as minimum requirement

### ISSUE THREAD

**Issue by jbostoen** [chillerlan/php-qrcode#257]
**Describe the documentation issue or addition**
It seems when using composer to install the latest php-qrcode, it actually uses the php-settings-container which now requires PHP 8.1.

**Proposed change/addition** (if applicable)

The documentation stated the 5.x release was still compatible with PHP 7.4. 
However, this seems not to be the case (by default) anymore.

**Additional context**

https://github.com/chillerlan/php-qrcode/releases/tag/4.4.0 explicitly mentions the 5.x branch should be compatible with PHP 7.4.

**Comment by codemasher** [comment]
Hi, thanks for the report! The `v5.x` branch uses a version switch for this dependency as its API is fully compatible, so if you're installing `php-qrcode` on PHP 8.1+ it will install the newer dependency.

https://github.com/chillerlan/php-qrcode/blob/da5bdb82c8755f54de112b271b402aaa8df53269/composer.json#L45

**Comment by codemasher** [comment]
The unit test would yell at me if it wasn't compatible with PHP 7.4 :)

https://github.com/chillerlan/php-qrcode/actions?query=branch%3Av4.3.x

**Comment by codemasher** [comment]
I'm going to close this here. Feel free to hop over to [the discussions section](https://github.com/chillerlan/php-qrcode/discussions) if you have further questions.
