### ISSUE TITLE
outputInterface option does not seem to work on last stable release [BUG]

### ISSUE THREAD

**Issue by dstallo** [chillerlan/php-qrcode#260]
**Describe the bug or unexpected behaviour**

On last stable release 5.0.2, the examples using outputInterface option (for instance svgWithLogoAndCustomShapes) does not generate the expected output. It seems to be ignoring outputInterface option.

**Steps to reproduce the behavior**

1) Create a new folder.
2) Install php-qrcode with  $ composer require chillerlan/php-qrcode
3) Copy examples folder to the project folder
4) Run php examples/svgWithLogoAndCustomShapes.php.

The generated svg is wrong. Does not have the github logo nor the custom modules or finder patterns.

**Expected behavior**

The generated svg should contain the github logo, the custom heart shaped modules and the rounded finder patterns.

**Environment:**

- PHP version/OS: 8.3 / Mac OS
- Library version: 5.0.2

**Additional context**

If instead of last stable version dev-main is used, every example works fine. This seems to be a problem with the last stable version.

**Comment by codemasher** [comment]
Hi, this is not a bug, [you're using incompatible examples from dev-main](https://github.com/chillerlan/php-qrcode?tab=readme-ov-file#documentation). See also https://github.com/chillerlan/php-qrcode/discussions/241#discussioncomment-8461662
