### ISSUE TITLE
Examples seem to be out of date

### ISSUE THREAD

**Issue by jakewhiteley** [chillerlan/php-qrcode#264]
**Describe the bug or unexpected behaviour**

The examples such as https://github.com/chillerlan/php-qrcode/blob/main/examples/image.php typically set options on the `QROptions` object, but the issue is they are pretty much all protected.

**Expected behavior**

If you want us to set properties on a `QROptions` instance, make them public or provide setters/getters.

**Comment by codemasher** [comment]
Have you actively tried our an example and/or read the linked documentation? https://github.com/chillerlan/php-settings-container#advanced-usage
