### ISSUE TITLE
I just want to save the file

### ISSUE THREAD

**Issue by ftrotter** [chillerlan/php-qrcode#27]
I do not want to display or output anything. 
I am sure there is a way, but I cannot easily see it in the documentation or the examples.

-FT

**Comment by zzplab** [comment]
[chillerlan/php-qrcode#advanced-usage](https://github.com/chillerlan/php-qrcode#advanced-usage) 
```
// ...with additional cache file
$qrcode->render($data, '/path/to/file.png');
```

**Comment by codemasher** [comment]
See #19.
Since [v3.0](https://github.com/chillerlan/php-qrcode/releases/tag/3.0.0) you can also issue a cache file path via `QRCode::render(string $data, string $file = null)`.
