### ISSUE TITLE
Bug in RegExp

### ISSUE THREAD

**Issue by robodal** [chillerlan/php-qrcode#282]
https://github.com/chillerlan/php-qrcode/blob/9964cf8ff1ad90d17c360bd320cf18e16cd59829/src/Data/AlphaNum.php#L30

https://onlinephp.io/c/215012

(bool)preg_match('#^[+-.]+$#', ',') = true
BUT
(bool)preg_match('#^[+.-]+$#', ',') = false

**Comment by robodal** [comment]
https://github.com/chillerlan/php-qrcode/blob/9964cf8ff1ad90d17c360bd320cf18e16cd59829/src/Data/AlphaNum.php#L39

**Comment by codemasher** [comment]
Oh, good catch. Some of those characters should be escaped, I guess I'll just regex that bit the regular way then.

**Comment by codemasher** [comment]
This is it. The minus it kind of problematic within the regex, it has to be in a specific position to not cause problems apparently, but also it can't be escaped as this would break the regex too.

```php
preg_match('/^[A-Z\d %$*+-.:\/]+$/', $string);
```
