### ISSUE TITLE
Help // How can i load the class in Laravel ?

### ISSUE THREAD

**Issue by jpasosa** [chillerlan/php-qrcode#29]
In the implement of this class in a controller of laravel i have this:
app/Http/Controllers/TestCodeQRController.php

```
<?php

// namespace App\Http\Controllers;
namespace chillerlan\QRCode;

use chillerlan\QRCode\QRCode;
use chillerlan\QRCode\QROptions;

class TestCodeQRController extends Controller
{

    function index():string
    {
        echo 'Testing code QR()';


        $data = 'otpauth://totp/test?secret=B3JX4VCVJDVNXNZ5&issuer=chillerlan.net';
        echo '<img src="'.(new QRCode)->render($data).'" />';



        return '';
    }

}
```

and the error is:
Class 'chillerlan\QRCode\Controller' not found

Can you help me ? Thanks a lot!

**Comment by codemasher** [comment]
You are in the wrong namespace - the commented first line in your script `App\Http\Controllers` is your working namespace, not `chillerlan\QRCode`.

**Comment by jpasosa** [comment]
Thanks @codemasher , i change to this:
```
namespace App\Http\Controllers;

use chillerlan\QRCode\{QRCode, QROptions};

```
