### ISSUE TITLE
QRCodeException - code length overflow

### ISSUE THREAD

**Issue by mira-kovar** [chillerlan/php-qrcode#31]
Hi,
I have problem with generating SVG QRCode. No matter which size I'm gettting `QRCodeException` Here is my content. It is valid QRCode content for Czech standart for QR Invoice (http://qr-faktura.cz/).

Please could you increase `MAX_BITS` or provide option to bypase?

```
SPD*1.0*ACC:CZ8620100000002000948394*AM:3025.00*CC:CZK*X-VS:1181273*X-SS:0*X-KS:308*MSG:1181273*DT:20190318*X-INV:SID%2A1.0%2ATB0%3A2500.00%2AT0%3A525.00%2AID%3A1181273%2ADD%3A20190304%2AINI%3A25520270%2AVII%3ACZ25520270%2AINR%3A24791334%2AVIR%3ACZ24791334%2ADUZP%3A20190304%2AAM%3A3025.00%2AVS%3A1181273%2ADT%3A20190318%2ACC%3ACZK%2AX-SW%3Acpilot.cz*
```

**Comment by codemasher** [comment]
I just tried the data you posted with the SVG example and it worked perfectly fine with `QRCode::VERSION_AUTO`. What is the value for `QROptions::$version` you're using? The minimum would be 12 for ECC type L according to `QRDataInterface::MAX_BITS`. See http://www.qrcode.com/en/about/version.html for more info on that.

**Comment by mira-kovar** [comment]
Aha! I used version 5, I works like charm. Thanks

**Comment by MichaMeyer** [comment]
Hi! We have a similar problem!
1.) We pass a URL for qr code creation: 
https://devel.abc-efg.com/Administrator/

it has a length of 40 Characters, we have chosen to use version 4 QR Code and ECC H
Specification says with ECC H **50 alphanumeric letters** are possible? 
![grafik](https://user-images.githubusercontent.com/32386846/226602628-cc47ae50-46fb-4210-81f0-2ddf87dfb3ca.png)


2.) My developers told me that the newest version of the library would not work, and that it was necessary to "combine" several versions of the lib and make own extensions in the lib?

They worked based on this:
https://github.com/chillerlan/php-qrcode/blob/main/examples/imageWithLogo.php

We just needed a normal QR Code with an Logo (with logospace around) inside and 

- variable colors for foreground, 
- background and 
- Background transparency. 

Is there any problem to create this with the latest version? 

And which one (stable or not?) should be used?

Would really appreciate your help!
