### ISSUE TITLE
Can I change the finder pattern

### ISSUE THREAD

**Issue by williams-young** [chillerlan/php-qrcode#32]
as the title says, Does the lib have this settings?

**Comment by codemasher** [comment]
Change the finder pattern in which way? You can change the colors, but the pattern itself is specified in the QR Code specification. https://www.thonky.com/qr-code-tutorial/module-placement-matrix

**Comment by de-iyasin** [comment]
> Change the finder pattern in which way? You can change the colors, but the pattern itself is specified in the QR Code specification. https://www.thonky.com/qr-code-tutorial/module-placement-matrix

@codemasher Hi, I want to change my finder and the body pixel pattern like the attached screenshot. Could you please help me with that?

![image](https://user-images.githubusercontent.com/93583662/144642589-77ec5d91-b599-436d-ba80-3381bd937641.png)

**Comment by codemasher** [comment]
Which output module are you using (png/svg/imagick)? I can tell you where about you need to make changes but you will need to implement them by yourself.

**Comment by iarafat** [comment]
@codemasher, Understood, Thank you for your response. I am using PNG output module.

**Comment by de-iyasin** [comment]
@codemasher, Understood, Thank you for your response. I am using PNG output module.

**Comment by codemasher** [comment]
Ok, for the current release you will need to extend the `QRImage` class and reimplement the [`dump()` method](https://github.com/chillerlan/php-qrcode/blob/main/src/Output/QRImage.php#L110-L114), specifically the loop over the matrix and the call to [`setPixel()`](https://github.com/chillerlan/php-qrcode/blob/05917f7286a9b050c60ff8a60685c329db4cda27/src/Output/QRImage.php#L136-L146). In the loop you can then intercept the modules of the finder pattern like so:
```php
foreach($this->matrix->matrix() as $y => $row){
	foreach($row as $x => $M_TYPE){
		// narrow down to the dark pixels of the finder pattern
		if($M_TYPE === QRMatrix::M_FINDER|QRMatrix::IS_DARK){
			// find the 1-3 pixels of the corners and do stuff
		}
		else{
			$this->setPixel($x, $y, $this->moduleValues[$M_TYPE]);
		}
	}
}
```
You can use [the code of the `QRMatrix`](https://github.com/chillerlan/php-qrcode/blob/05917f7286a9b050c60ff8a60685c329db4cda27/src/Data/QRMatrix.php#L234-L246) to locate the corners of the finder patterns and alter the appearance using [the GD image functions](https://www.php.net/manual/en/function.imagefilledarc), similar to the `setPixel()` method.
