### ISSUE TITLE
Where's Wally?

### ISSUE THREAD

**Issue by eborguezao** [chillerlan/php-qrcode#34]
Whats the reason for monopolizing the implementation with the composer? 'vendor', wheres Wally?

**Comment by codemasher** [comment]
https://getcomposer.org/doc/05-repositories.md#package

**Comment by eborguezao** [comment]
Make no mistake, it would not be so special for the effort, I'm new indeed. Thanks for the reference.

**Comment by codemasher** [comment]
Look, if you come here and utter something about "monopolizing" without apparently understanding what composer is and also seemingly didn't type "php composer" into an internet search engine of your choice, then i'm not very eager to help. If you don't understand the basic concepts of package management, you may also ask the internet. If you want to complain about "monopolizing", well, go ahead, complain to GitHub, Packagist, NPM et cetera. Good luck.

**Comment by eborguezao** [comment]
Reducing time with the composer is a must for yesterday, but it's not the issue. But your code becomes useless in porting on a media and (trying) to use in an environment without network access. It was exhausting, thank you.

**Comment by codemasher** [comment]
That again is not my problem, neither that of this library, nor package management in general. Where's the problem installing the package the way it is intended on a system with online access, then copy the whole directory where you want to use it? None of that is exhausting - it's a matter of minutes.

**Comment by eborguezao** [comment]
Even your answers are 'socks'.
