### ISSUE TITLE
Additional text to the QR

### ISSUE THREAD

**Issue by tomtopweb** [chillerlan/php-qrcode#35]
Is it possible to add additional text to the QR image or under of the QR code?

**Comment by codemasher** [comment]
How exactly do you mean? Can you please provide an example?

**Comment by tomtopweb** [comment]
! [QR example] (https://user-images.githubusercontent.com/11610896/59944049-19ae3b00-9464-11e9-9438-87f83ca0a37a.jpg)

I'm looking for such things, such as a QR code, with some different text (value) such as an ID or a name. It is much easier to identify QR codes when printing out them.

**Comment by codemasher** [comment]
Ah, thank you! That's quite simple. You could either extend `QRImage` (or `QRImagick` respectively) and create a new image with your text and copy the qrcode into it, or you can use the return value of the `dump()` method to do the same externally. I could provide you with a simple example tomorrow.

**Comment by codemasher** [comment]
So i made a little example with room for improvements (unicode, font size, true type font etc.) but i think you get the gist of it: [`QRImageWithText`](https://github.com/chillerlan/php-qrcode/blob/master/examples/QRImageWithText.php) and [`imageWithText.php`](https://github.com/chillerlan/php-qrcode/blob/master/examples/imageWithText.php). Good luck!
![image](https://user-images.githubusercontent.com/592497/59965168-c04d1700-950a-11e9-854c-29592a04863f.png)

**Comment by tomtopweb** [comment]
Woww, thank you very much for the example and help! :)

**Comment by tomtopweb** [comment]
Could you please check this as using your example giving this error and not sure where to fix.
![2019-06-28](https://user-images.githubusercontent.com/11610896/60354904-9cd41180-99cd-11e9-97e4-db24e3addbbf.png)

**Comment by codemasher** [comment]
Do you by chance have the full debug output and/or your code that causes it?

**Comment by tomtopweb** [comment]
I'm using like this, please check:

`function generate_qr_code_with_text()
    {

        $data = 'https://www.youtube.com/watch?v=DLzxrzFCyOs&t=43s';
        $options = new QROptions([
            'version'      => 7,
            'outputType'   => QRCode::OUTPUT_IMAGE_PNG,
            'scale'        => 3,
            'imageBase64'  => false,
        ]);
        header('Content-type: image/png');
        $qrOutputInterface = new QRImageWithText($options, (new QRCode($options))->getMatrix($data));
        echo $qrOutputInterface->dump(null, 'example text');
    }`

**Comment by tomtopweb** [comment]
Did you have a chance to look at the code?

**Comment by ilkerkocatepe** [comment]
Hello,
Firstly thank you for this generator.
I have a problem with ImageWithText.
I have no problem with normal Image Generator; but when I tried the image with text, don't show anything.
Best regards

**Comment by codemasher** [comment]
@ilkerkocatepe what exactly is the problem? I just ran that example locally and it seems to work fine. (hint: outcomment the `header('Content-type: image/png');` line to see the error message if you're running the example in a browser).

**Comment by ilkerkocatepe** [comment]
Hi again,
`Fatal error: Uncaught Error: Class 'chillerlan\QRCode\QRImageWithText' not found `

I'm getting this. Thank you.

**Comment by codemasher** [comment]
Ah, this helps! It is because this an example and the class is in the `chillerlan\QRCodeExamples` namespace, which is only loaded with dev dependencies. You would need to create this class in your own applications namespace (copy the example class and change its namespace to your application's) and run it from there.

**Comment by ilkerkocatepe** [comment]
Thank you @codemasher It's great. It solved 👌

**Comment by codemasher** [comment]
Happy to help!
