### ISSUE TITLE
Generate QR from raw binary data

### ISSUE THREAD

**Issue by Synchro** [chillerlan/php-qrcode#39]
I'm looking to generate QR codes from raw binary data rather than text, as it makes for much more compact codes - for example a timestamp value (from `time()`) as text is at least 10 bytes, but as raw data is only 4 (`pack('L', time())`), but this QR code renderer dies when given raw data like that. It it possible to disable character set semantics and accept raw binary input with this package?

**Comment by codemasher** [comment]
Hi! I took a quick look into it and it seems like the encoder goes into Kanji mode which results in scrambled output. I then forced it into byte mode and the output looked like expected, like so:

```php
class ByteQRCode extends QRCode{
	public function initDataInterface(string $data):QRDataInterface{
		return new Byte($this->options, $data);
	}
}
```

However, the data will still be scrambled unless the QRCode reader is able to decode the binary data - the ZXing on Android just displays `|��]`.

**Comment by Synchro** [comment]
Thanks, that should do it. The reader is under my control too so I don't need general compatibility. I'm looking to convey about 50 chars of text data, but it drops to 28 in binary, meaning I can afford to spend more on higher redundancy or larger pixels.

**Comment by codemasher** [comment]
Happy to help!

**Comment by codemasher** [comment]
I've added an [option to override the data mode](https://github.com/chillerlan/php-qrcode/commit/df33b38b6348ba96e2bf2207d7b0ca6ce3e506f4) as it might be useful for others, e.g. when the auto detection fails for some reason. You can install it via [version 3.2.0](https://github.com/chillerlan/php-qrcode/releases/tag/3.2.0). You can then set `$qrOptions->dataMode = 'Byte';` and pass the options instance to the `QRCode` constructor as usual.

**Comment by Synchro** [comment]
Thanks!
