### ISSUE TITLE
Works locally but not on server

### ISSUE THREAD

**Issue by charlesmudy** [chillerlan/php-qrcode#41]
Hi,

Thanks for the great lib :)

Everything works fine locally but doesn't seem to work on my server (Ubuntu 18.4 on Digital Ocean).

I have tried checking and installing the php7.3 extension one by one but still no success.

Can you help with a lead?

**Comment by codemasher** [comment]
Hi, do you have any error messages or console output? The extensions GD, mbstring and json are required for the installation.

**Comment by charlesmudy** [comment]
Sorry for my late response and thanks for your prompt response.

I'm getting this `Message: Class 'Chillerlan\QRCode\QROptions' not found` but it's the same setting I have locally that works

**Comment by codemasher** [comment]
Hmm, that sounds like the composer autoloader isn't working correctly. Have you included `vendor/autoload.php` somewhere?

**Comment by charlesmudy** [comment]
Yes I did and here is what I included:

`use chillerlan\QRCode\QRCode;`
`use chillerlan\QRCode\QROptions;`

Just works locally...

**Comment by codemasher** [comment]
Still, it looks like the autoloader can't resolve the library's path.

**Comment by charlesmudy** [comment]
I am a bit lost on what to do next. At least it seems like `use chillerlan\QRCode\QRCode;` is working fine.

**Comment by charlesmudy** [comment]
I'm a bit lost on what to do next. Other libs are working fine.

Can you please point me to any direction?

**Comment by codemasher** [comment]
With the only clue i have, that is an error message hinting that the autoloader isn't working properly, i can only help you that much. So how did you install the library: copy over from your local installation or `composer install` on the reote with your own composer.json (or maybe even global composer installation)? Is there maybe a path mismatch somewhere?

I assume you have composer installed globally on your remote server - create a new directory somewhere and store the following as `composer.json`, then run `composer install` in that directory, which creates a `./vendor` directory, containing the libraries and autoloader.
```json
{
	"minimum-stability": "stable",
	"require": {
		"php": "^7.2",
		"chillerlan/php-qrcode": "^3.2"
	}
}
```
Then create a `test.php` in the same directory with the following content:
```php
<?php

use chillerlan\QRCode\{QRCode, QROptions};

require_once __DIR__.'/vendor/autoload.php';

$options = new QROptions(['outputType' => QRCode::OUTPUT_STRING_TEXT]);

echo (new QRCode($options))->render('test');
```
Now run `php test.php`. Good luck!

**Comment by charlesmudy** [comment]
Weird but for some reason ... the `php-qrcode` was empty.

Thanks a lot for your guidance.
