### ISSUE TITLE
PostgresSQL Connect Bug

### ISSUE THREAD

**Issue by YgorMarcelinodaSilva** [chillerlan/php-qrcode#46]
When trying to save the QRCode image in the database (POSTGRES) it generates the error:
Fatal error: Uncaught Error: Class 'chillerlan \ QRCodeExamples \ Bank' not found in C: \ xampp \ htdocs \ testeQRcode \ cadEvento.php: 29 Stack trace: # 0 {main} thrown in C: \ xampp \ htdocs \ testQRcode \ cadEvento.php on line 29

I wonder if the library supports PostgresSQL

**Comment by codemasher** [comment]
Excuse me what? This is not an error related to this library - there's something going wrong in your code.

**Comment by YgorMarcelinodaSilva** [comment]
Thank you, that was exactly my question


Em qua., 15 de abr. de 2020 às 21:06, smiley <notifications@github.com>
escreveu:
