### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by MalteKiefer** [chillerlan/php-qrcode#50]
Hello,

maybe I am to stupid to find it out, but how can I change to qrcode from black to orange?
Thanks

**Comment by codemasher** [comment]
Hi, please see this example: https://github.com/chillerlan/php-qrcode/blob/main/examples/image.php

**Comment by MalteKiefer** [comment]
Thanks it works.
Is it possible to at a image, like a logo in the QrCode?

**Comment by codemasher** [comment]
I had it planned at some point but didn't yet bother to implement it.
