### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by rubensbarreto** [chillerlan/php-qrcode#54]
With the official release of php 8, will we have support for it?

Currently adding it using composer fails:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.                               

  Problem 1
    - Installation request for chillerlan/php-qrcode 3.3 -> satisfiable by chillerlan/php-qrcode[3.3.0].
    - chillerlan/php-qrcode 3.3.0 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.

Regards,

**Comment by codemasher** [comment]
PHP8 is supported as of v4.2 (7.4+). In case you need to support PHP versions lower than 7.4, you can use a version switch in `composer.json`, like `"chillerlan/php-qrcode": "^3.4 || ^4.3"`.
