### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by louis123562** [chillerlan/php-qrcode#55]
Hey,

is it possible to generate a QR-Code with a white background?

At the moment all have transparent background and when display in an email with enabled dark-mode, it is almost impossible to even see the qr-code (Outlook for Android).

Thank you, Louis

**Comment by codemasher** [comment]
Hey! Sure there is an option for it - just set `QROptions::$imageTransparent` to `false` et voilà!

**Comment by louis123562** [comment]
Great - works as expected :)

Thank you

```
$options = new QROptions([
    'imageTransparent'    => false
]);

(new QRCode($options))->render("https://github.com");
```
