### ISSUE TITLE
SVG output lines between paths

### ISSUE THREAD

**Issue by ipetak** [chillerlan/php-qrcode#57]
Hi,

I've noticed that outputting the QR code as SVG generates SVG with lines that look like borders on some squares. I haven't managed to figure out what exactly those lines are, stroke, outline or just misalignment of paths, it seems like they are transparent. Here is a screenshot of SVG versus the PNG output so its easier to notice what I'm talking about.

![SVG QR code](https://user-images.githubusercontent.com/11562076/103693127-140e3c80-4f99-11eb-9be1-0aebd6b133bb.png)

![PNG QR code](https://user-images.githubusercontent.com/11562076/103693167-225c5880-4f99-11eb-9065-9087a9f6d342.png)

My QR options are: 
_
'version'     => 6,
'eccLevel'    => QRCode::ECC_L,
'outputType'  => QRCode::OUTPUT_MARKUP_SVG,
'imageBase64' => false
_

Can you try recreating the issue and looking into it please, maybe I'm doing something wrong. Thank you ahead!

**Comment by codemasher** [comment]
Hey, it seems that's rather a browser issue, specifically rendering. The distance between the blocks should be 0 and there should not be a visible line regardless. I can see these lines too and it also depends on the browser's current zoom and changes with the zoom level, in both, chrome and firefox. As for the generation: at least the blocks of the same color in the same line should be connected and i found a bug that prevents this. I'll look into it as soon as i can but it's low priority as i'm currently [revamping some internals](https://github.com/chillerlan/php-qrcode/tree/v5). I can leave the issue open and tag it as "help needed" as i don't know too much about SVG to find an easy way how to fix it (one of which would be to connect *all* modules of the same color). Right now i can only suggest to use png output in case it's bothering.

**Comment by IvanPetakNeuralab** [comment]
Sounds good, thanks for the fast response I'll use the PNG temporary and probably dig a bit more about the issue itself. Again thank you for the help.

**Comment by codemasher** [comment]
I'm currently working on an overhaul of the SVG output module and honestly i have absolutely no idea where these lines come from. I'll check this off as rendering issue which is beyond my powers to fix. In the current iteration I'm rendering each module individually and one would expect the lines between each then, but instead they just seem to appear randomly:
![image](https://user-images.githubusercontent.com/592497/144518915-b8baa937-7bd0-4012-8eb7-1fdb852a9c7e.png)

Having individual modules however has its perks: a nice way to circumvent the line issue (and - surprisingly - there are no visible lines between the few square blocks!?)
![image](https://user-images.githubusercontent.com/592497/144519104-a40cab25-897e-4074-8783-92cb345733cf.png)

So I'm going to close this issue for now.

**Comment by ipetak** [comment]
Great! Thank you for taking the time to look into this. Awesome work!
