### ISSUE TITLE
Wkhtml2pdf -> Does not render SVG Correctly [With Solution]

### ISSUE THREAD

**Issue by mfrederico** [chillerlan/php-qrcode#66]
Using WKHTML2PDF does not render the SVG at all.  It comes up blank.

This is due to the extra **%** in the svgHeader string:

QRMarkup.php Line 30
-------------------
```
    protected string $svgHeader = '<svg xmlns="http://www.w3.org/2000/svg" class="qr-svg %1$s" '.
                                  'style="width: 100%**%**; height: auto;" viewBox="0 0 %2$d %2$d">';
```

**Comment by codemasher** [comment]
The second percent sign is there as escape because this piece of code is *always* run through [sprintf](https://www.php.net/manual/en/function.sprintf):

https://github.com/chillerlan/php-qrcode/blob/be3beb936c21fe53a4e7e8f7f3582e9f02443666/src/Output/QRMarkup.php#L26-L30

**Comment by codemasher** [comment]
Can you please post a snippet of the code you're using? I'm somehow suspecting that it's caused by the base64 data URI output (which is default).
