### ISSUE TITLE
Dependencies of release 3.4.1 breaks compatibility with php 7.2

### ISSUE THREAD

**Issue by fduarte42** [chillerlan/php-qrcode#94]
Latest php 7.2 release 3.4.1 requires module "chillerlan/php-settings-container" which requires php 7.4 and breaks compatibility.

Can you please fix this?

**Comment by codemasher** [comment]
Um i don't think so? How does your `composer.json` look? Do you have an example and/or console output from composer?
https://github.com/chillerlan/php-qrcode/blob/468603b687a5fe75c1ff33857a45f1726c7b95a9/composer.json#L29
https://github.com/chillerlan/php-qrcode/runs/3508700328
https://packagist.org/packages/chillerlan/php-qrcode#3.4.1
