### ISSUE TITLE
4.3.2 throws deprecated warning in PHP 8.1

### ISSUE THREAD

**Issue by Klopfer1402** [chillerlan/php-qrcode#97]
I know this is all reworked in 5, but maybe worth fixing in 4.3: This line throws a warning in PHP 8.1 as passing null to strtolower is deprecated. Should be an easy fix.

https://github.com/chillerlan/php-qrcode/blob/d8b03878805967e6de57a8ba23772d8166fa5194/src/QRCode.php#L218

**Comment by codemasher** [comment]
Thank you for the report! I've pushed a little fix to the 4.3.x branch, but I'll wait for the official 8.1 release to tag it just in case it may introduce other issues.
